name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Verify
    uses: maveniverse/parent/.github/workflows/ci.yml@release-57
    with:
      # we do separate IT with mvn3 and mvn4; no need for matrix
      maven-matrix: '[ "3.9.16" ]'
      maven-test: './mvnw clean verify -e -B -V -P run-its -f it'
